//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntregasTardias
    {
        public int ID { get; set; }
        public Nullable<int> PrestamoID { get; set; }
        public Nullable<System.DateTime> FechaEntregaTardia { get; set; }
    
        public virtual Prestamos Prestamos { get; set; }
    }
}
