//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Prestamos()
        {
            this.EntregasTardias = new HashSet<EntregasTardias>();
        }
    
        public int ID { get; set; }
        public string CedulaColaborador { get; set; }
        public string CodigoHerramienta { get; set; }
        public Nullable<System.DateTime> FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaCompromisoDevolucion { get; set; }
        public Nullable<System.DateTime> FechaEntrega { get; set; }
    
        public virtual Colaboradores Colaboradores { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntregasTardias> EntregasTardias { get; set; }
        public virtual Herramientas Herramientas { get; set; }
    }
}
